import argparse
import json
import sys
from pathlib import Path

if __package__ is None or __package__ == "":
    repo_root = Path(__file__).resolve().parents[1]
    if str(repo_root) not in sys.path:
        sys.path.insert(0, str(repo_root))

from inference.io import render_multilayer_clouds_from_hdf5


DEFAULT_CONFIG_PATH = Path(__file__).resolve().parents[1] / "configs" / "pdgcn_infer.example.json"


def main(argv=None):
    parser = argparse.ArgumentParser(description="Render multilayer PD-GCN HDF5 results to VTK clouds.")
    parser.add_argument(
        "--config",
        default=str(DEFAULT_CONFIG_PATH),
        help="Inference JSON config used to resolve the default prediction HDF5 path.",
    )
    parser.add_argument(
        "--prediction",
        default=None,
        help="Prediction HDF5 generated by inference/infer_entry.py. Defaults to inference.output_path in --config.",
    )
    parser.add_argument("--cloud-interval", type=int, default=None, help="Optional VTK output interval override.")
    parser.add_argument("--vtk-output-dir", default=None, help="Optional VTK output directory override.")
    parser.add_argument(
        "--max-nodes-per-layer",
        type=int,
        default=None,
        help="Unsupported for topology wedge rendering; omit this option to preserve mesh connectivity.",
    )
    args = parser.parse_args(argv)
    prediction_path = args.prediction or _prediction_path_from_config(args.config)

    result = render_multilayer_clouds_from_hdf5(
        prediction_path,
        cloud_interval=args.cloud_interval,
        vtk_output_dir=args.vtk_output_dir,
        max_nodes_per_layer=args.max_nodes_per_layer,
    )
    print(f"vtk_output_dir: {result['vtk_output_dir']}")
    print(f"render_seconds: {result['render_seconds']:.6f}")
    print(f"rendered_steps: {result['rendered_steps']}")
    return 0


def _prediction_path_from_config(config_path):
    config_path = Path(config_path).resolve()
    payload = json.loads(config_path.read_text(encoding="utf-8"))
    if not isinstance(payload, dict):
        raise ValueError("inference config JSON must contain an object at the top level.")
    inference = payload.get("inference")
    if not isinstance(inference, dict):
        raise ValueError("inference config JSON must contain an 'inference' object.")
    output_path = inference.get("output_path")
    if not isinstance(output_path, str) or not output_path:
        raise ValueError("inference.output_path must be a non-empty string.")
    path = Path(output_path)
    if path.is_absolute():
        return path
    return (config_path.parent / path).resolve()


if __name__ == "__main__":
    raise SystemExit(main())
