import argparse
import sys
from pathlib import Path

if __package__ is None or __package__ == "":
    repo_root = Path(__file__).resolve().parents[1]
    if str(repo_root) not in sys.path:
        sys.path.insert(0, str(repo_root))

from inference.io import render_multilayer_clouds_from_hdf5


def main(argv=None):
    parser = argparse.ArgumentParser(description="Render multilayer PD-GCN HDF5 results to VTK clouds.")
    parser.add_argument("--prediction", required=True, help="Prediction HDF5 generated by inference/infer_entry.py.")
    parser.add_argument("--cloud-interval", type=int, default=None, help="Optional VTK output interval override.")
    parser.add_argument("--vtk-output-dir", default=None, help="Optional VTK output directory override.")
    parser.add_argument(
        "--max-nodes-per-layer",
        type=int,
        default=None,
        help="Unsupported for topology wedge rendering; omit this option to preserve mesh connectivity.",
    )
    args = parser.parse_args(argv)

    result = render_multilayer_clouds_from_hdf5(
        args.prediction,
        cloud_interval=args.cloud_interval,
        vtk_output_dir=args.vtk_output_dir,
        max_nodes_per_layer=args.max_nodes_per_layer,
    )
    print(f"vtk_output_dir: {result['vtk_output_dir']}")
    print(f"render_seconds: {result['render_seconds']:.6f}")
    print(f"rendered_steps: {result['rendered_steps']}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
